version: '3.2'

services:
  compatibilityanalyzer.service:
    image: compatibilityanalyzer.service
    build:
      context: ./src/CompatibilityAnalyzer.Service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    ports:
        - "80:80"

  compatibilityanalyzer:
    image: compatibilityanalyzer
    build:
      context: ./src/CompatibilityAnalyzer
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    volumes:
      - "c:\\data\\refs:/refs:ro"

  mongo:
    container_name: dev_mongo
    image: mongo:3.4.10

  rabbitmq:
    container_name: dev_rabbit
    image: rabbitmq:3.6.12-alpine