version: '3'

services:
  compatibilityanalyzer.service:
    image: compatibilityanalyzer.service
    build:
      context: ./src/CompatibilityAnalyzer.Service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    ports:
        - "80:80"

  compatibilityanalyzer:
    image: compatibilityanalyzer
    build:
      context: ./src/CompatibilityAnalyzer
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq

  rabbitmq:
    container_name: dev_rabbit
    image: rabbitmq:3.6.12-alpine