// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Model.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CompatibilityAnalyzer.Models.Protobuf {

  /// <summary>Holder for reflection information generated from Model.proto</summary>
  internal static partial class ModelReflection {

    #region Descriptor
    /// <summary>File descriptor for Model.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ModelReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtNb2RlbC5wcm90byI1CgtSZXF1ZXN0SXRlbRIeCgVudWdldBgBIAEoCzIN",
            "Lk51R2V0UmVxdWVzdEgAQgYKBGl0ZW0iOQoMTnVHZXRSZXF1ZXN0EgwKBEZl",
            "ZWQYASABKAkSCgoCaWQYAiABKAkSDwoHdmVyc2lvbhgDIAEoCSJbCg5BbmFs",
            "eXplUmVxdWVzdBIKCgJpZBgBIAEoCRIeCghvcmlnaW5hbBgCIAEoCzIMLlJl",
            "cXVlc3RJdGVtEh0KB3VwZGF0ZWQYAyABKAsyDC5SZXF1ZXN0SXRlbUIoqgIl",
            "Q29tcGF0aWJpbGl0eUFuYWx5emVyLk1vZGVscy5Qcm90b2J1ZmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CompatibilityAnalyzer.Models.Protobuf.RequestItem), global::CompatibilityAnalyzer.Models.Protobuf.RequestItem.Parser, new[]{ "Nuget" }, new[]{ "Item" }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CompatibilityAnalyzer.Models.Protobuf.NuGetRequest), global::CompatibilityAnalyzer.Models.Protobuf.NuGetRequest.Parser, new[]{ "Feed", "Id", "Version" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CompatibilityAnalyzer.Models.Protobuf.AnalyzeRequest), global::CompatibilityAnalyzer.Models.Protobuf.AnalyzeRequest.Parser, new[]{ "Id", "Original", "Updated" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  internal sealed partial class RequestItem : pb::IMessage<RequestItem> {
    private static readonly pb::MessageParser<RequestItem> _parser = new pb::MessageParser<RequestItem>(() => new RequestItem());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RequestItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CompatibilityAnalyzer.Models.Protobuf.ModelReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestItem(RequestItem other) : this() {
      switch (other.ItemCase) {
        case ItemOneofCase.Nuget:
          Nuget = other.Nuget.Clone();
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestItem Clone() {
      return new RequestItem(this);
    }

    /// <summary>Field number for the "nuget" field.</summary>
    public const int NugetFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CompatibilityAnalyzer.Models.Protobuf.NuGetRequest Nuget {
      get { return itemCase_ == ItemOneofCase.Nuget ? (global::CompatibilityAnalyzer.Models.Protobuf.NuGetRequest) item_ : null; }
      set {
        item_ = value;
        itemCase_ = value == null ? ItemOneofCase.None : ItemOneofCase.Nuget;
      }
    }

    private object item_;
    /// <summary>Enum of possible cases for the "item" oneof.</summary>
    public enum ItemOneofCase {
      None = 0,
      Nuget = 1,
    }
    private ItemOneofCase itemCase_ = ItemOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ItemOneofCase ItemCase {
      get { return itemCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearItem() {
      itemCase_ = ItemOneofCase.None;
      item_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RequestItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RequestItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Nuget, other.Nuget)) return false;
      if (ItemCase != other.ItemCase) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (itemCase_ == ItemOneofCase.Nuget) hash ^= Nuget.GetHashCode();
      hash ^= (int) itemCase_;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (itemCase_ == ItemOneofCase.Nuget) {
        output.WriteRawTag(10);
        output.WriteMessage(Nuget);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (itemCase_ == ItemOneofCase.Nuget) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Nuget);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RequestItem other) {
      if (other == null) {
        return;
      }
      switch (other.ItemCase) {
        case ItemOneofCase.Nuget:
          Nuget = other.Nuget;
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            global::CompatibilityAnalyzer.Models.Protobuf.NuGetRequest subBuilder = new global::CompatibilityAnalyzer.Models.Protobuf.NuGetRequest();
            if (itemCase_ == ItemOneofCase.Nuget) {
              subBuilder.MergeFrom(Nuget);
            }
            input.ReadMessage(subBuilder);
            Nuget = subBuilder;
            break;
          }
        }
      }
    }

  }

  internal sealed partial class NuGetRequest : pb::IMessage<NuGetRequest> {
    private static readonly pb::MessageParser<NuGetRequest> _parser = new pb::MessageParser<NuGetRequest>(() => new NuGetRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<NuGetRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CompatibilityAnalyzer.Models.Protobuf.ModelReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NuGetRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NuGetRequest(NuGetRequest other) : this() {
      feed_ = other.feed_;
      id_ = other.id_;
      version_ = other.version_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NuGetRequest Clone() {
      return new NuGetRequest(this);
    }

    /// <summary>Field number for the "Feed" field.</summary>
    public const int FeedFieldNumber = 1;
    private string feed_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Feed {
      get { return feed_; }
      set {
        feed_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 2;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 3;
    private string version_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Version {
      get { return version_; }
      set {
        version_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as NuGetRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(NuGetRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Feed != other.Feed) return false;
      if (Id != other.Id) return false;
      if (Version != other.Version) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Feed.Length != 0) hash ^= Feed.GetHashCode();
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Version.Length != 0) hash ^= Version.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Feed.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Feed);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Id);
      }
      if (Version.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Version);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Feed.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Feed);
      }
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Version.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Version);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(NuGetRequest other) {
      if (other == null) {
        return;
      }
      if (other.Feed.Length != 0) {
        Feed = other.Feed;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Version.Length != 0) {
        Version = other.Version;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Feed = input.ReadString();
            break;
          }
          case 18: {
            Id = input.ReadString();
            break;
          }
          case 26: {
            Version = input.ReadString();
            break;
          }
        }
      }
    }

  }

  internal sealed partial class AnalyzeRequest : pb::IMessage<AnalyzeRequest> {
    private static readonly pb::MessageParser<AnalyzeRequest> _parser = new pb::MessageParser<AnalyzeRequest>(() => new AnalyzeRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AnalyzeRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CompatibilityAnalyzer.Models.Protobuf.ModelReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AnalyzeRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AnalyzeRequest(AnalyzeRequest other) : this() {
      id_ = other.id_;
      Original = other.original_ != null ? other.Original.Clone() : null;
      Updated = other.updated_ != null ? other.Updated.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AnalyzeRequest Clone() {
      return new AnalyzeRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "original" field.</summary>
    public const int OriginalFieldNumber = 2;
    private global::CompatibilityAnalyzer.Models.Protobuf.RequestItem original_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CompatibilityAnalyzer.Models.Protobuf.RequestItem Original {
      get { return original_; }
      set {
        original_ = value;
      }
    }

    /// <summary>Field number for the "updated" field.</summary>
    public const int UpdatedFieldNumber = 3;
    private global::CompatibilityAnalyzer.Models.Protobuf.RequestItem updated_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CompatibilityAnalyzer.Models.Protobuf.RequestItem Updated {
      get { return updated_; }
      set {
        updated_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AnalyzeRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AnalyzeRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(Original, other.Original)) return false;
      if (!object.Equals(Updated, other.Updated)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (original_ != null) hash ^= Original.GetHashCode();
      if (updated_ != null) hash ^= Updated.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (original_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Original);
      }
      if (updated_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Updated);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (original_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Original);
      }
      if (updated_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Updated);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AnalyzeRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.original_ != null) {
        if (original_ == null) {
          original_ = new global::CompatibilityAnalyzer.Models.Protobuf.RequestItem();
        }
        Original.MergeFrom(other.Original);
      }
      if (other.updated_ != null) {
        if (updated_ == null) {
          updated_ = new global::CompatibilityAnalyzer.Models.Protobuf.RequestItem();
        }
        Updated.MergeFrom(other.Updated);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (original_ == null) {
              original_ = new global::CompatibilityAnalyzer.Models.Protobuf.RequestItem();
            }
            input.ReadMessage(original_);
            break;
          }
          case 26: {
            if (updated_ == null) {
              updated_ = new global::CompatibilityAnalyzer.Models.Protobuf.RequestItem();
            }
            input.ReadMessage(updated_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
